export const CREATE_ITEM = 'CREATE_ITEM'
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS'
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'

